version: "3.8"

services:
  aihr-localstack:
    container_name: aihr-localstack
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - './backend/localstack/setup-localstack.sh:/docker-entrypoint-initaws.d/setup.sh'
  aihr-backend:
    container_name: aihr-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7000
    ports:
      - 7000:7000
    depends_on:
      - aihr-localstack
